asm_translation_loader.admin.index:
    path: /
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:list

asm_translation_loader.admin.list:
    path: /list
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:list

asm_translation_loader.admin.form:
    path: /form/{key}/{locale}/{domain}
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:form
        key: ~
        locale: ~
        domain: ~

asm_translation_loader.admin.create:
    path: /create
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:create
    methods: [POST]

asm_translation_loader.admin.read:
    path: /edit
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:read
    methods: [POST]

asm_translation_loader.admin.update:
    path: /update
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:update
    methods:  [POST]

asm_translation_loader.admin.delete:
    path: /delete
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:delete
    methods: [POST]
