asm_translation_loader.admin.index:
    path: /
    defaults:
        _controller: asm_translation_loader.translation_controller:listAction

asm_translation_loader.admin.list:
    path: /list
    defaults:
        _controller: asm_translation_loader.translation_controller:listAction

asm_translation_loader.admin.form:
    path: /form/{key}/{locale}/{domain}
    defaults:
        _controller: asm_translation_loader.translation_controller:formAction
        key: ~
        locale: ~
        domain: ~

asm_translation_loader.admin.create:
    path: /create
    defaults:
        _controller: asm_translation_loader.translation_controller:createAction
    methods: [POST]

asm_translation_loader.admin.update:
    path: /update
    defaults:
        _controller: asm_translation_loader.translation_controller:updateAction
    methods:  [POST]

asm_translation_loader.admin.delete:
    path: /delete
    defaults:
        _controller: asm_translation_loader.translation_controller:deleteAction
    methods: [POST]
