asm_translation_loader.admin.index:
    path: /index
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:index

asm_translation_loader.admin.create:
    path: /create
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:create

asm_translation_loader.admin.read:
    path: /get/{trans_key}/{trans_locale}/{message_domain}
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:read

asm_translation_loader.admin.update:
    path: /update
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:update

asm_translation_loader.admin.delete:
    path: /delete/{trans_key}/{trans_locale}/{message_domain}
    defaults:
        _controller: AsmTranslationLoaderBundle:Translation:delete
