parameters:
    asm_translation_loader.translation_loader_class:  'Asm\TranslationLoaderBundle\Translation\DatabaseLoader'

services:
    # database loader
    translation.loader.db:
        class:     '%asm_translation_loader.translation_loader_class%'
        arguments: [ '@asm_translation_loader.translation_manager' ]
        tags:
            - { name: translation.loader, alias: db}
